name: Publish to npm

on:
  release:
    types: [created] # Runs when a new GitHub Release is created

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # Ensure latest stable version is installed

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm --filter ./packages/file-uploader build # Build only the package to publish

      - name: Publish to npm
        run: pnpm --filter ./packages/file-uploader publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
